// ═══════════════════════════════════════════════════════════════════════════
// MatchingCortex — learned stereo matcher using an MLP
//
// Replaces classical stereo matching (BM, SGM) with a trained MLP
// that predicts disparity + confidence for each grid position.
//
// Architecture: 164 → 64 → 2
//   Input:  left patch (9×9=81) + right patch (81) + position (row, col) = 164
//   Output: disparity (sigmoid × maxDisparity), confidence (sigmoid [0,1])
//
// The MLP runs per grid cell (not per pixel) — the grid is typically
// 36 columns × 1 row for navigation, so 36 evaluations per frame.
//
// Uses @spiky-panda/core's PerceptronBuilder and MLPInferenceRuntime
// for consistency with PerceptCortex and DecisionCortex.
// ═══════════════════════════════════════════════════════════════════════════

import {
    ActivationFunctions,
    Glorot,
    ILayerConnectionBuilder,
    IMlpGraph,
    LayerConnectionBuilder,
    LayerConnectionType,
    MLPInferenceRuntime,
    MlpSynapse,
    PerceptronBuilder,
    SynapseBuilder,
} from "@spiky-panda/core";

import { ComputeNodeBase } from "./compute.nodes";
import { ITensor } from "@dev/spiky-panda/compute";

// ─── Constants ───────────────────────────────────────────────────────────────

/** Patch size: 9×9 pixels per camera = 81 values. */
export const MATCHING_PATCH_SIZE = 9;
export const MATCHING_PATCH_AREA = MATCHING_PATCH_SIZE * MATCHING_PATCH_SIZE;

/** Input size: left patch + right patch + position (row, col). */
export const MATCHING_INPUT_SIZE = MATCHING_PATCH_AREA * 2 + 2; // 164

/** Output size: disparity + confidence. */
export const MATCHING_OUTPUT_SIZE = 2;

/** Hidden layer size. */
export const MATCHING_HIDDEN_SIZE = 64;

// ─── Graph factory ───────────────────────────────────────────────────────────

function createMatchingCortexGraph(): IMlpGraph {
    const createConnBuilder = function (fanin: number, fanout: number): ILayerConnectionBuilder {
        const synapseBuilder = new SynapseBuilder().withType(MlpSynapse) as SynapseBuilder;
        return new LayerConnectionBuilder()
            .withSynapseBuilder(synapseBuilder)
            .withType(LayerConnectionType.FullyConnected)
            .withWeightInitializer(new Glorot(fanin, fanout));
    };

    const builder = new PerceptronBuilder()
        .withInputLayer(MATCHING_INPUT_SIZE, 0, ActivationFunctions.linear)
        .withHiddenLayer(MATCHING_HIDDEN_SIZE, 0, ActivationFunctions.tanh)
        .withConnectionBuilder(createConnBuilder(MATCHING_INPUT_SIZE, MATCHING_HIDDEN_SIZE))
        .withOutputLayer(MATCHING_OUTPUT_SIZE, 0, ActivationFunctions.sigmoid)
        .withConnectionBuilder(createConnBuilder(MATCHING_HIDDEN_SIZE, MATCHING_OUTPUT_SIZE));

    // Total params: 164×64 + 64×2 + 64 + 2 = 10,626 + 66 = 10,694
    return builder.build();
}

// ─── MatchingCortex compute node ─────────────────────────────────────────────

/**
 * Configuration for the MatchingCortex.
 */
export interface IMatchingCortexConfig {
    /** Maximum disparity value in pixels. Output[0] = sigmoid × maxDisparity. Default: 128. */
    maxDisparity: number;

    /** Number of grid columns to evaluate. Default: 36 (NAVIGATOR_LIDAR_SECTORS). */
    gridCols: number;

    /** Number of grid rows to evaluate. Default: 1 (single horizontal beam). */
    gridRows: number;

    /** Image width of the stereo pair (for patch extraction). */
    imageWidth: number;

    /** Image height of the stereo pair. */
    imageHeight: number;
}

/**
 * MLP-based stereo matching as a compute node.
 *
 * Receives a stereo pair tensor (left + right images concatenated)
 * and produces a depth tensor by evaluating the MLP at each grid
 * position.
 *
 * **Why MLP over BM/SGM?**
 * - Learns to handle textureless surfaces (from training data)
 * - Learns lighting-invariant matching
 * - Trainable on domain-specific data (Martian terrain)
 * - Same infrastructure as PerceptCortex (spiky-panda MLPTrainingRuntime)
 *
 * **Trade-offs:**
 * - 10,694 params × 36 evaluations per frame = ~384K multiply-adds
 *   (~0.4ms, acceptable at 30 Hz)
 * - Needs training data (generated by MathStereoSimulator)
 * - Less generalizable than SGM to unseen scenes (but more robust
 *   to specific failure modes when trained on them)
 */
export class MatchingCortexNode extends ComputeNodeBase {
    public readonly nodeType = "matching_cortex";
    public readonly outputShapes: number[][];

    private readonly _graph: IMlpGraph;
    private readonly _runtime: MLPInferenceRuntime;
    private readonly _config: IMatchingCortexConfig;

    constructor(config: IMatchingCortexConfig) {
        super();
        this.id = "matching_cortex";
        this._config = config;
        this._graph = createMatchingCortexGraph();
        this._runtime = new MLPInferenceRuntime(this._graph);
        this.outputShapes = [[config.gridCols * config.gridRows]];
    }

    /** Access the MLP graph for training or weight loading. */
    public get graph(): IMlpGraph {
        return this._graph;
    }

    /** Access the runtime for direct inference. */
    public get runtime(): MLPInferenceRuntime {
        return this._runtime;
    }

    /**
     * Execute stereo matching.
     *
     * @param inputs  Expected: single tensor containing the stereo pair.
     *                Shape: [H, W, 2] where channel 0 = left, channel 1 = right.
     *                Or: [H * W * 2] flattened (left image followed by right image).
     * @returns       Single tensor: depth values per grid cell, shape [gridCols * gridRows].
     */
    public execute(inputs: ITensor[]): ITensor[] {
        const { gridCols, gridRows, imageWidth, imageHeight, maxDisparity } = this._config;
        const totalCells = gridCols * gridRows;
        const depthOutput = new Float32Array(totalCells);

        if (inputs.length === 0 || inputs[0].data.length === 0) {
            return [{ data: depthOutput, shape: [totalCells], name: "stereo_depth" }];
        }

        const stereoData = inputs[0].data;
        const pixelCount = imageWidth * imageHeight;

        // Split into left and right images
        const leftImage = stereoData.subarray(0, pixelCount);
        const rightImage = stereoData.subarray(pixelCount, pixelCount * 2);

        const halfPatch = Math.floor(MATCHING_PATCH_SIZE / 2);
        const cellW = imageWidth / gridCols;
        const cellH = imageHeight / gridRows;

        for (let row = 0; row < gridRows; row++) {
            for (let col = 0; col < gridCols; col++) {
                // Center pixel of this grid cell
                const cx = Math.floor((col + 0.5) * cellW);
                const cy = Math.floor((row + 0.5) * cellH);

                // Extract patches (9×9 around center, clamped to image bounds)
                const mlpInput = new Array<number>(MATCHING_INPUT_SIZE);
                let idx = 0;

                // Left patch
                for (let py = -halfPatch; py <= halfPatch; py++) {
                    for (let px = -halfPatch; px <= halfPatch; px++) {
                        const ix = Math.max(0, Math.min(cx + px, imageWidth - 1));
                        const iy = Math.max(0, Math.min(cy + py, imageHeight - 1));
                        mlpInput[idx++] = leftImage[iy * imageWidth + ix];
                    }
                }

                // Right patch (at same position — the MLP learns the offset)
                for (let py = -halfPatch; py <= halfPatch; py++) {
                    for (let px = -halfPatch; px <= halfPatch; px++) {
                        const ix = Math.max(0, Math.min(cx + px, imageWidth - 1));
                        const iy = Math.max(0, Math.min(cy + py, imageHeight - 1));
                        mlpInput[idx++] = rightImage[iy * imageWidth + ix];
                    }
                }

                // Normalized position
                mlpInput[idx++] = row / Math.max(gridRows - 1, 1);
                mlpInput[idx++] = col / Math.max(gridCols - 1, 1);

                // Run MLP
                const output = this._runtime.run(mlpInput);

                // output[0] = sigmoid → disparity (0 to maxDisparity)
                // output[1] = sigmoid → confidence (0 to 1)
                const disparity = output[0] * maxDisparity;
                const confidence = output[1];

                // Convert disparity to depth (0 if no match / low confidence)
                if (disparity > 0.5 && confidence > 0.3) {
                    // Depth is inversely proportional to disparity
                    // The actual baseline/focal conversion is handled upstream
                    depthOutput[row * gridCols + col] = 1.0 / disparity;
                }
                // else: remains 0 (no valid match)
            }
        }

        return [{ data: depthOutput, shape: [totalCells], name: "stereo_depth" }];
    }

    /**
     * Apply mutations to the MLP weights (for evolutionary training).
     */
    public mutate(weightScale: number = 0.1, biasScale: number = 0.05): void {
        for (const syn of this._graph.links) {
            syn.weight += (Math.random() * 2 - 1) * weightScale;
        }
        for (const node of this._graph.nodes) {
            node.bias += (Math.random() * 2 - 1) * biasScale;
        }
    }
}
